@startuml "reportingcontainer"
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

' increasing the allowable size of the text to be displayed without wrap
' skinparam wrapWidth 300

' remove unnecessary `container` type text from the rendered elements
LAYOUT_WITH_LEGEND()

title 
<b>Container Diagram for Reporting System</b>
end title

System_Ext(raw_data_provider, "Raw data provider", "Provides reservation, guest, and POS transaction raw data")

System_Boundary(reportingsystem, "Reporting System") {
    ContainerQueue(raw_data_topic, "Data Topic", "Kafka", "Stores reservation, guest, and POS transaction raw data for 7 days")
    Container(raw_data_processor, "Data Processor", "Java, Kafka Streams", "Ingests, enriches and aggregates raw data")
    ContainerDb(reporting_data_store, "Reporting Data Store", "MongoDB", "Stores reservation, guest, and POS transaction data")
    Container(reporting_api, "Reporting API", "Java, Spring Boot", "Provides APIs for users to query reports")
}

Person(internal_user, "Internal user(stakeholder)")
Person_Ext(external_user, "External user(restaurant owner)")

Rel_D(raw_data_provider, raw_data_topic, "Produces", "Kafka")

Rel_R(raw_data_topic, raw_data_processor, "Consumes", "Kafka")
Rel_R(raw_data_processor, reporting_data_store, "Reads/Writes", "MongoDB")
Rel_L(reporting_api, reporting_data_store, "Queries", "MongoDB")

Rel_U(internal_user, reporting_api, "Queries", "json/HTTPS")
Rel_U(external_user, reporting_api, "Queries", "json/HTTPS")
@enduml